name: Lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
